package login;

import gerentecompra.inicio;
import compras.InicioCompras;
import entidades.User;
import logico.UserLog;
import ventas.Inventario;
import static login.Login.UserName;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cardiell
 */
public class CargarUser extends javax.swing.JFrame implements Runnable{
    private Thread tiempo = null;
    User acceso;
    UserLog login;
    /**
     * Creates new form CargarUser
     */
    public CargarUser() {
        initComponents();
        setLocationRelativeTo(null);
        login = new UserLog();
        tiempo = new Thread(this);
        tiempo.start();
    }
    
    private void AccesoDepartamento()
    {
        acceso = login.ListarLogin(UserName);
        System.out.println("Rol: "+acceso.getIdRol()+" Departamento: "+acceso.getIdDepartamento());
        if(acceso.getIdRol()!= 1){
        switch(acceso.getIdDepartamento())
        {
            case 1://Ventas
                    switch(acceso.getIdRol())
                    {
                        case 3:
                                this.dispose();
                                new inicio(acceso.getIdDepartamento()).setVisible(true);//Este es ara Gerente
                        break;
                        case 4:
                                this.dispose();
                                 new InicioCompras(acceso.getIdDepartamento()).setVisible(true);// Y este pra Administrativ
                        break;
                        default:
                                JOptionPane.showMessageDialog(null,"El rol no se encuentra asginado en el Departamento");
                        break;
                    }
            break;
            
            case 2: //Compras
                    switch(acceso.getIdRol())
                    {
                        case 3:
                                //this.dispose();
                                //new VentasGerente.setVisible(true);
                        break;
                        case 4:
                                this.dispose();
                                new Inventario().setVisible(true);
                        break;
                        default:
                                JOptionPane.showMessageDialog(null,"El rol no se encuentra asginado en el Departamento");
                        break;
                    }
            break;
            
            case 3:
                    switch(acceso.getIdRol())
                    {
                        case 3:
                                //this.dispose();
                                //new MantenimientoGerente().setVisible(true);
                        break;
                        case 4:
                                //this.dispose();
                                //new Mantenimiento().setVisible(true);
                        break;
                        default:
                                JOptionPane.showMessageDialog(null,"El rol no se encuentra asginado en el Departamento");
                        break;
                    }
            break;
            
            case 4:
                   switch(acceso.getIdRol())
                    {

                        case 5:
                                //this.dispose();
                                //new AlmacenSupervisor().setVisible(true);
                        break;
                        
                        case 6:
                                //this.dispose();
                                //new AlmacenOperador().setVisible(true);
                        default:
                                JOptionPane.showMessageDialog(null,"El rol no se encuentra asginado en el Departamento");
                        break;
                    }
            break;
            
            case 5:
                   switch(acceso.getIdRol())
                    {
                        case 5:
                                //this.dispose();
                                //new ProduccionSupervisor().setVisible(true);
                        break;
                        case 6:
                                //this.dispose();
                                //new ProduccionOperador().setVisible(true);
                        default:
                                JOptionPane.showMessageDialog(null,"El rol no se encuentra asginado en el Departamento");
                        break;
                    }
            break;       
        }
        }
       // this.dispose();
        //new Admin().setVisible(true);
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(390, 370));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 20, 112, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loaduser2.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 160, 150, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 390, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

        @Override
        public void run() 
        {
            while(tiempo != null)
            {
                try 
                {
                    Thread.sleep(2500);
                    this.dispose();
                    AccesoDepartamento();
                    Thread.sleep(2500);
                    tiempo = null;
                } catch (InterruptedException ex) 
                {
                    Logger.getLogger(InicioCompras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }    
        }
}
