 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras;


import entidades.User;
import entidades.Departamento;
import entidades.Compra;
import entidades.Proveedor;
import logico.UserLog;
import logico.ComprasLog;
import logico.ProveedorLog;
import dao.ProveedoresDao;
import dao.ComprasDao;
import modelotabla.ModeloTablaCompras;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import comandos.cmd;
import logico.DepartamentoLog;
import static compras.InicioCompras.idDepartamento;

/**
 *
 * @author alberto jaquez
 */
public class Pedimento extends javax.swing.JDialog {
   int i =0;
   ComprasLog comlog;
   ProveedorLog proveedor;
   UserLog user;
   DepartamentoLog departamento;
   Compra compras;
   ProveedoresDao proveedores;
   Date Dates;
   ComprasDao compradao;
   ModeloTablaCompras modeloTabla;
   cmd cm;
    /**
     * Creates new form Pedimento
     */         
           
           
    public Pedimento(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBounds(400,200,750,550);
        comlog= new ComprasLog();
        proveedor = new ProveedorLog();
        departamento = new DepartamentoLog();
        user = new UserLog();
        cm = new cmd();
        listarMaterial();
        listarProveedores();
        listaruser();
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        Dates = new java.sql.Date(lnMilisegundos);
        lblFecha.setText(String.valueOf(Dates));
        
        //txtuser.setText();
    }
     public void IngresarCompra() throws SQLException
    {
       
        String nombre = (String) cbuser.getSelectedItem();
        String articulo = (String) cbarticulo.getSelectedItem();
        String proveedor = (String) cbProveedor.getSelectedItem();
        Compra temp = comlog.SelectPresupuesto(articulo);
        float precio = temp.getPrecio();
        Departamento tmp = departamento.BuscarDepartamento(idDepartamento);
        float presupuesto= tmp.getPresupuesto();
                   
            if(!comlog.OkUser(nombre))
               JOptionPane.showMessageDialog(null, "No existe el nombre en la BD");
           else if(!comlog.OkArticulo(articulo) )
               JOptionPane.showMessageDialog(null, "No existe el articulo en la BD");
           else if(!comlog.OkProveedores(proveedor))
               JOptionPane.showMessageDialog(null, "No existe el proveedor en la BD"); 
            if(Text_Cantidad.getText().isEmpty()==false){
   
               int cantidad = Integer.parseInt(Text_Cantidad.getText());
                 if((precio*cantidad)>presupuesto)
                    JOptionPane.showMessageDialog(null, "No Alcanza cuentas con:"+presupuesto+"y son:"+(precio*cantidad));
                 else{
                compras = new Compra(nombre,Dates,cantidad,articulo,proveedor);
                presupuesto -=(precio*cantidad);
                Departamento dep = new Departamento(idDepartamento,tmp.getDescripcion(),presupuesto);
                
                   if (!comlog.AgregarCompra(compras)) {
                        departamento.UpdateDepartamento(dep);
                        JOptionPane.showMessageDialog(null, "Información Agregada.");
                        dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al agregar la Información.");
                    System.exit(0);
                }
                 }
           }else
                JOptionPane.showMessageDialog(null,"Favor de introducir una Cantidad");

               
 
    } 
     public void listarMaterial()
     {
        List<Compra> listas = comlog.ListarPedimento();
        int i =0;
        while(i<listas.size())
        cbarticulo.addItem(listas.get(i++).getNombreArticulo());
      
     }        
     public void listarProveedores()
     {
       List<Proveedor> listas = proveedor.ListarProveedor();
       int i = 0;
       while(i<listas.size())
          cbProveedor.addItem(listas.get(i++).getNombreCompania());
           
         
     }
     public void listaruser(){
         List<User> listas = user.ListarUser();
         int i =0;
         while(i<listas.size())
             cbuser.addItem(listas.get(i++).getNameUser());
     }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        Text_Cantidad = new javax.swing.JTextField();
        cbarticulo = new javax.swing.JComboBox<>();
        cbProveedor = new javax.swing.JComboBox<>();
        cbuser = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(741, 502));
        setMinimumSize(new java.awt.Dimension(741, 502));
        setPreferredSize(new java.awt.Dimension(741, 502));
        getContentPane().setLayout(null);

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFecha);
        lblFecha.setBounds(610, 15, 100, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitud de compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 60, 185, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 10, 60, 28);
        jLabel2.getAccessibleContext().setAccessibleName("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 90, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Articulo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 80, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 100, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Proveedor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(27, 290, 110, 28);

        btnAtras.setBackground(new java.awt.Color(51, 51, 51));
        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Regresar");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(380, 410, 110, 37);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mattel10.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 0, 100, 110);

        btnGenerar.setBackground(new java.awt.Color(51, 51, 51));
        btnGenerar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Registrar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar);
        btnGenerar.setBounds(240, 410, 110, 37);

        Text_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_CantidadKeyTyped(evt);
            }
        });
        getContentPane().add(Text_Cantidad);
        Text_Cantidad.setBounds(130, 250, 590, 28);

        getContentPane().add(cbarticulo);
        cbarticulo.setBounds(130, 210, 590, 28);

        getContentPane().add(cbProveedor);
        cbProveedor.setBounds(130, 290, 590, 28);

        getContentPane().add(cbuser);
        cbuser.setBounds(130, 170, 590, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orig_506983.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(741, 502));
        jLabel7.setMinimumSize(new java.awt.Dimension(741, 502));
        jLabel7.setPreferredSize(new java.awt.Dimension(741, 502));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 750, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try 
        {
           IngresarCompra();
        }catch (SQLException ex) {
           Logger.getLogger(Pedimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void Text_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_CantidadKeyTyped
        
        char car = evt.getKeyChar();
        if((car < '0' || car > '9') && (car != '\b'))       
                evt.consume(); 
        
        if(car == '\b')
            i--;
        
        if(Text_Cantidad.getText().isEmpty())
	i=0;
        if(i>8) 
             evt.consume();
        i++;
    }//GEN-LAST:event_Text_CantidadKeyTyped

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pedimento dialog = new Pedimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_Cantidad;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JComboBox<String> cbarticulo;
    private javax.swing.JComboBox<String> cbuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFecha;
    // End of variables declaration//GEN-END:variables

}