/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import entidades.CotizarMaterial;
import entidades.Material;
import logico.CotizarMaterialLog;
import logico.MaterialLog;
import static ventas.Inventario.idCotizar;
import static ventas.ClienteUsuario.reg;
import static ventas.Inventario.contenedorModulos;
import static ventas.Inventario.cot;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Cardiell
 */
public class CotizacionFrame extends javax.swing.JInternalFrame implements Runnable{
int y=0;
MaterialLog material;
CotizarMaterialLog cotizaciones;
List<CotizarMaterial> Precotiz;
Thread hilo;
    /**
     * Creates new form Cotizacion
     */
    public CotizacionFrame(){
        initComponents();
        int i=0;
        material = new MaterialLog();
        cotizaciones = new CotizarMaterialLog();
        Precotiz= cotizaciones.ListarCotizarMaterial(idCotizar);
        hilo = new Thread(this);
        hilo.start();
        if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                MostrarPanels(Precotiz.get(i));
                i++;
            }
        }


    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelCotizar = new javax.swing.JPanel();
        PanelSubTotal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalProd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        lblpanel2 = new javax.swing.JLabel();
        lblpanel1 = new javax.swing.JLabel();
        lblpanel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1166, 740));
        setMinimumSize(new java.awt.Dimension(1166, 740));
        setPreferredSize(new java.awt.Dimension(1166, 740));
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        PanelCotizar.setBackground(new java.awt.Color(255, 255, 255));
        PanelCotizar.setPreferredSize(new java.awt.Dimension(300, 300));
        PanelCotizar.setLayout(null);

        PanelSubTotal.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setText("Subtotal");
        PanelSubTotal.add(jLabel5);
        jLabel5.setBounds(20, 20, 100, 20);

        lblTotalProd.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        lblTotalProd.setText("(34 productos):");
        PanelSubTotal.add(lblTotalProd);
        lblTotalProd.setBounds(120, 20, 200, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("$");
        PanelSubTotal.add(jLabel8);
        jLabel8.setBounds(20, 60, 11, 20);

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(153, 0, 0));
        lblSubtotal.setText("98454.00");
        PanelSubTotal.add(lblSubtotal);
        lblSubtotal.setBounds(31, 60, 230, 20);

        btnPago.setBackground(new java.awt.Color(240, 183, 79));
        btnPago.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnPago.setText("Proceder al Pago");
        btnPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        PanelSubTotal.add(btnPago);
        btnPago.setBounds(20, 120, 250, 35);

        PanelCotizar.add(PanelSubTotal);
        PanelSubTotal.setBounds(800, 30, 300, 175);

        lblpanel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblpanel2.setText("Precio");
        PanelCotizar.add(lblpanel2);
        lblpanel2.setBounds(520, 53, 40, 17);

        lblpanel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblpanel1.setText("Cant.");
        PanelCotizar.add(lblpanel1);
        lblpanel1.setBounds(680, 53, 40, 17);

        lblpanel3.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        lblpanel3.setText("Cotizacion");
        PanelCotizar.add(lblpanel3);
        lblpanel3.setBounds(10, 35, 120, 25);

        jScrollPane1.setViewportView(PanelCotizar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1150, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        if(!lblSubtotal.getText().equalsIgnoreCase("0.0")){
            
            reg=null;
            ClienteUsuario addCont = new ClienteUsuario(null,true);
            addCont.setVisible(true);
            addCont.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            addCont.setAlwaysOnTop(true);
        }else
            JOptionPane.showMessageDialog(this,"No hay ningun articulo favor de anadir Articulos");
    }//GEN-LAST:event_btnPagoActionPerformed

    
    public void MostrarPanels(CotizarMaterial cotizacion){   
        Material tmp =material.BuscarMaterialesId(cotizacion.getIdMaterial());
        panelMostrar = new JPanel();
        lblImagen = new JLabel();
        lblNombreMat = new JLabel();
        JLabel lblEliminar = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jSeparator1 = new JSeparator();
        JTextField txtCantidad = new JTextField();
        panelMostrar.setBackground(new java.awt.Color(255, 255, 255));
        panelMostrar.setLayout(null);

        lblImagen.setIcon(new javax.swing.ImageIcon(tmp.getImagen())); // NOI18N
        panelMostrar.add(lblImagen);
        lblImagen.setBounds(10, 15, 170, 160);

        lblNombreMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreMat.setText(tmp.getNombreMaterial());
        panelMostrar.add(lblNombreMat);
        lblNombreMat.setBounds(210, 30, 260, 50);

        lblEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(0, 153, 153));
        lblEliminar.setText("Eliminar");
        lblEliminar.setToolTipText("");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.setFocusable(false);
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lblEliminar.setForeground(new java.awt.Color(204, 102, 0));
                    Font font = lblEliminar.getFont();
                    Map attributes = font.getAttributes();
                    attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                    lblEliminar.setFont(font.deriveFont(attributes));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminar.setForeground(new java.awt.Color(0, 153, 153));
                lblEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            }
            
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                lblEliminarMousePressed(evt,tmp);
            }
        });
        panelMostrar.add(lblEliminar);
        lblEliminar.setBounds(210, 110, 50, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("$");
        panelMostrar.add(jLabel2);
        jLabel2.setBounds(500, 40, 11, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText(String.valueOf(tmp.getPrecio()));
        panelMostrar.add(jLabel3);
        jLabel3.setBounds(513, 40, 90, 20);
        panelMostrar.add(jSeparator1);
        jSeparator1.setBounds(10, 2, 780, 10);

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCantidad.setText(String.valueOf(cotizacion.getCantidad()));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    char caracter = evt.getKeyChar(); //Optiene las teclas presionadas
                    if(((caracter < '0') ||
                      (caracter > '9')) &&
                      (caracter != '\b'))
                    {
                            evt.consume();
                    }
                    int cantidad;
                    if(!txtCantidad.getText().isEmpty()){
                        cantidad=Integer.valueOf(txtCantidad.getText());
                    
                         if(caracter == KeyEvent.VK_ENTER)
                         {
                            CotizarMaterial cot= new CotizarMaterial(idCotizar,cotizacion.getIdMaterial(),cantidad);
                            Actualizar(cot,cantidad,tmp);
                         }
                    }
                }                
            });
                
        panelMostrar.add(txtCantidad);
        txtCantidad.setBounds(670, 40, 80, 30);
        PanelCotizar.add(panelMostrar);
        panelMostrar.setBounds(0, 70+y, 800, 175);
        y+=220;
        PanelCotizar.setPreferredSize(new Dimension(1130,0+y));
        pack();

    }

    
        private void lblEliminarMousePressed(java.awt.event.MouseEvent evt,Material tmp) {                                       
               int i=0;
               y=0;
                cotizaciones.EliminarCotizarMaterial(idCotizar,tmp.getIdMaterial());
                this.dispose();
                        Runtime garbage = Runtime.getRuntime();
                        garbage.gc();
                    cot= new CotizacionFrame();
                    contenedorModulos.add(cot);
                    contenedorModulos.getDesktopManager().maximizeFrame(cot);
                    cot.setVisible(true);  
                        garbage.gc();
        }    

        public void Actualizar(CotizarMaterial coti,int cantidad,Material tmp){
            if(tmp.getExistencia()>=cantidad){
            cotizaciones.UpdateCotizarMaterial(coti);
            this.dispose();
                        Runtime garbage = Runtime.getRuntime();
                        garbage.gc();
                        cot= new CotizacionFrame();
                    contenedorModulos.add(cot);
                    contenedorModulos.getDesktopManager().maximizeFrame(cot);
                    cot.setVisible(true);  
                   garbage.gc();
            }else
                JOptionPane.showMessageDialog(this,"Cantidad insuficiente hay solo "+tmp.getExistencia()+" piezas");

        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCotizar;
    private javax.swing.JPanel PanelSubTotal;
    private javax.swing.JButton btnPago;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotalProd;
    private javax.swing.JLabel lblpanel1;
    private javax.swing.JLabel lblpanel2;
    private javax.swing.JLabel lblpanel3;
    // End of variables declaration//GEN-END:variables
    private JPanel panelMostrar;
    private JLabel lblImagen;
    private JLabel lblNombreMat;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JSeparator jSeparator1;

    @Override
    public void run() {
         int total=0;
         int cantidad;
         float precio;
         float subtotal=0;
         int i=0;
         Material tmp;
        if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                cantidad=Precotiz.get(i).getCantidad();
                tmp =material.BuscarMaterialesId(Precotiz.get(i).getIdMaterial());
                
                precio = tmp.getPrecio();
                 total+= cantidad;
                 subtotal+=(precio*cantidad);
                i++;
            }
        }
        lblTotalProd.setText("("+total+" Productos):");
        lblSubtotal.setText(String.valueOf(subtotal));
        
    }
}
