/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import entidades.Cotizacion;
import entidades.CotizarMaterial;
import entidades.Factura;
import entidades.Material;
import logico.CotizacionLog;
import logico.CotizarMaterialLog;
import logico.FacturaLog;
import logico.MaterialLog;
import static ventas.Inventario.idCotizar;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author Cardiell
 */
public class FacturaFrame extends javax.swing.JInternalFrame implements Runnable{
int y=0;
float APagar;
FacturaLog factura;
MaterialLog material;
CotizarMaterialLog cotizaciones;
List<CotizarMaterial> Precotiz;
    /**
     * Creates new form FacturaFrame
     */
    public FacturaFrame() {
        initComponents();
        factura = new FacturaLog();
        material = new MaterialLog();
        cotizaciones = new CotizarMaterialLog();
        List<Factura> fac = factura.ListarFactura();
        Factura tmp = fac.get(fac.size()-1);
        lblNoFactura.setText(String.valueOf(tmp.getNum_factura()));
        lblFechaFactura.setText(tmp.getFecha().toString());
        lblFechaVence.setText(tmp.getFechaVence());
        Precotiz= cotizaciones.ListarCotizarMaterial(tmp.getIdCotizar());
        int i=0;
        Thread hilo = new Thread(this);
        hilo.start();                
        if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                MostrarCosa(Precotiz.get(i));
                i++;
            }
        }        
        lblTotalAPagar.setText(String.valueOf(APagar));
        MostrarPanelTotal();
        CotizacionLog cotiz = new CotizacionLog();
        List<Cotizacion> cot = cotiz.ListarCotizacion();
        Cotizacion y = new Cotizacion(cot.size()+1);
        idCotizar = cot.size()+1;
        cotiz.AgregarCotizacion(y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelFactura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblNoFactura = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFechaFactura = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFechaVence = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Factura");
        setMaximumSize(new java.awt.Dimension(1204, 810));
        setMinimumSize(new java.awt.Dimension(1204, 810));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(800, 740));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 740));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 740));

        panelFactura.setBackground(new java.awt.Color(255, 255, 255));
        panelFactura.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        panelFactura.setMaximumSize(new java.awt.Dimension(800, 740));
        panelFactura.setMinimumSize(new java.awt.Dimension(800, 740));
        panelFactura.setPreferredSize(new java.awt.Dimension(800, 740));
        panelFactura.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mattel10.png"))); // NOI18N
        panelFactura.add(jLabel1);
        jLabel1.setBounds(650, 20, 110, 120);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Lic. Alejandro Torres");
        panelFactura.add(jLabel2);
        jLabel2.setBounds(50, 120, 140, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Bellas Artes No. 20308 ");
        panelFactura.add(jLabel3);
        jLabel3.setBounds(50, 140, 150, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Ciudad Industrial");
        panelFactura.add(jLabel4);
        jLabel4.setBounds(50, 155, 100, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Tijuana, Baja California ");
        panelFactura.add(jLabel5);
        jLabel5.setBounds(50, 170, 170, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Factura");
        panelFactura.add(jLabel6);
        jLabel6.setBounds(540, 200, 90, 15);
        panelFactura.add(jSeparator1);
        jSeparator1.setBounds(530, 220, 230, 10);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("No. de Factura");
        panelFactura.add(jLabel7);
        jLabel7.setBounds(540, 230, 100, 14);

        lblNoFactura.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblNoFactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoFactura.setText("1");
        panelFactura.add(lblNoFactura);
        lblNoFactura.setBounds(700, 230, 60, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Fecha de Factura");
        panelFactura.add(jLabel8);
        jLabel8.setBounds(540, 260, 100, 14);

        lblFechaFactura.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblFechaFactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaFactura.setText("23/05/2018");
        panelFactura.add(lblFechaFactura);
        lblFechaFactura.setBounds(690, 260, 70, 14);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("Fecha de Vencimiento");
        panelFactura.add(jLabel10);
        jLabel10.setBounds(540, 290, 130, 14);

        lblFechaVence.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblFechaVence.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaVence.setText("14/06/2018");
        panelFactura.add(lblFechaVence);
        lblFechaVence.setBounds(690, 290, 70, 14);

        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("A Pagar");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 9, 70, 15);

        lblTotalAPagar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTotalAPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAPagar.setText("565545");
        jPanel3.add(lblTotalAPagar);
        lblTotalAPagar.setBounds(97, 9, 113, 15);

        panelFactura.add(jPanel3);
        jPanel3.setBounds(540, 310, 220, 30);

        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Descripcion");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 14, 79, 15);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Cantidad");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(326, 14, 62, 15);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Precio");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(455, 14, 42, 15);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Importe");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(612, 14, 54, 15);

        panelFactura.add(jPanel4);
        jPanel4.setBounds(50, 390, 710, 40);

        jScrollPane1.setViewportView(panelFactura);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 20, 880, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1188, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarPanelTotal(){
        JPanel panelTotal = new JPanel();
        JPanel jPanel5 = new JPanel();
        JSeparator jSeparator2 = new JSeparator();
        JSeparator jSeparator3 = new JSeparator();
        JLabel jLabel17 = new JLabel();
        JLabel jLabel18 = new JLabel();
        JLabel jLabel19 = new JLabel();
        JLabel jLabel20 = new JLabel();
        JLabel jLabel21 = new JLabel();
        JLabel jLabel22 = new JLabel();
        JLabel jLabel23 = new JLabel();
        JLabel jLabel24 = new JLabel();
        JLabel jLabel25 = new JLabel();
        JLabel jLabel26 = new JLabel();
        JLabel jLabel27 = new JLabel();
        JLabel jLabel28 = new JLabel();
        JLabel jLabel29 = new JLabel();

        panelTotal.setBackground(new java.awt.Color(255, 255, 255));
        panelTotal.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Subtotal sin IVA");
        panelTotal.add(jLabel17);
        jLabel17.setBounds(10, 11, 89, 15);
        panelTotal.add(jSeparator2);
        jSeparator2.setBounds(10, 32, 242, 10);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("2650");
        panelTotal.add(jLabel18);
        jLabel18.setBounds(162, 11, 90, 15);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Descuento");
        panelTotal.add(jLabel19);
        jLabel19.setBounds(10, 48, 61, 15);
        panelTotal.add(jSeparator3);
        jSeparator3.setBounds(10, 69, 242, 10);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("34");                                                      // % descuento
        panelTotal.add(jLabel20);
        jLabel20.setBounds(77, 48, 14, 15);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("%");
        panelTotal.add(jLabel21);
        jLabel21.setBounds(97, 48, 14, 15);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("-54");                                                 // Valor del descuento
        panelTotal.add(jLabel22);
        jLabel22.setBounds(162, 48, 90, 15);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("IVA");
        panelTotal.add(jLabel23);
        jLabel23.setBounds(10, 85, 19, 15);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("21");                                                   // % IVA
        panelTotal.add(jLabel24);
        jLabel24.setBounds(35, 85, 14, 15);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("% de");
        panelTotal.add(jLabel25);
        jLabel25.setBounds(55, 85, 28, 15);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("2650");                                               // Total del IVA
        panelTotal.add(jLabel26);
        jLabel26.setBounds(89, 85, 55, 15);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("54353");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelTotal.add(jLabel27);
        jLabel27.setBounds(162, 85, 90, 15);

        jPanel5.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setText("Total");                                            
        jPanel5.add(jLabel28);
        jLabel28.setBounds(5, 8, 50, 22);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText(String.valueOf(APagar));                                                    //Total a pagar
        jPanel5.add(jLabel29);
        jLabel29.setBounds(80, 8, 160, 22);

        panelTotal.add(jPanel5);
        jPanel5.setBounds(10, 106, 242, 35);

        panelFactura.add(panelTotal);
        y+=80;
        panelTotal.setBounds(540, 450+y, 260, 160);
        y+=200;
        panelFactura.setPreferredSize(new Dimension(800,500+y));
        pack();  

    }
    
    private void MostrarCosa(CotizarMaterial temp){
        Material tmp =material.BuscarMaterialesId(temp.getIdMaterial());
        JPanel panelInfo = new JPanel();
        JPanel panelInterno1 = new JPanel();
        JPanel panelInterno2 = new JPanel();
        JPanel panelInterno3 = new JPanel();
        JPanel panelInterno4 = new JPanel();
        JLabel lblNombreMat = new JLabel();
        JLabel lblPrecio = new JLabel();
        JLabel lblCantidad = new JLabel();
        JLabel lblImporte = new JLabel();

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInfo.setLayout(null);

        panelInterno1.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInterno1.setLayout(null);

        lblNombreMat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreMat.setText(tmp.getNombreMaterial());
        panelInterno1.add(lblNombreMat);
        lblNombreMat.setBounds(11, 13, 278, 15);

        panelInfo.add(panelInterno1);
        panelInterno1.setBounds(0, 0, 300, 40);

        panelInterno2.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInterno2.setLayout(null);

        lblPrecio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText(String.valueOf(tmp.getPrecio()));
        panelInterno2.add(lblPrecio);
        lblPrecio.setBounds(40, 13, 31, 15);

        panelInfo.add(panelInterno2);
        panelInterno2.setBounds(420, 0, 120, 40);
        panelInterno3.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInterno3.setLayout(null);

        lblCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText(String.valueOf(temp.getCantidad()));
        panelInterno3.add(lblCantidad);
        lblCantidad.setBounds(37, 13, 49, 15);

        panelInfo.add(panelInterno3);
        panelInterno3.setBounds(300, 0, 120, 40);

        panelInterno4.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelInterno4.setLayout(null);

        lblImporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblImporte.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImporte.setText(String.valueOf(tmp.getPrecio()*temp.getCantidad()));
        panelInterno4.add(lblImporte);
        lblImporte.setBounds(11, 13, 148, 15);

        panelInfo.add(panelInterno4);
        panelInterno4.setBounds(540, 0, 170, 40);

        panelFactura.add(panelInfo);
        panelInfo.setBounds(50, 430+y, 710, 40);
        y+=40;
        panelFactura.setPreferredSize(new Dimension(800,460+y));
        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFechaFactura;
    private javax.swing.JLabel lblFechaVence;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JPanel panelFactura;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
  int total=0;
         int cantidad;
         float precio;
         float subtotal=0;
         int i=0;
         Material tmp;
        if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                cantidad=Precotiz.get(i).getCantidad();
                tmp =material.BuscarMaterialesId(Precotiz.get(i).getIdMaterial());
                
                 precio = tmp.getPrecio();
                 total+= cantidad;
                 subtotal+=(precio*cantidad);
                i++;
            }
        }
        APagar=subtotal;
        
    }        
}
