package ventas;

import entidades.Material;
import logico.MaterialLog;
import modelotabla.ModeloTablaMaterial;
import modelotabla.Table_Img;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;

/**
 *
 * @author Cardiell
 * @author JaquezAl
 */
public class MaterialesFrame extends javax.swing.JInternalFrame {
MaterialLog material;
boolean presionado=false;
ModeloTablaMaterial modeloTabla;
Material  mat;

    /**
     * Creates new form Computadoras
     */

    public MaterialesFrame() { //Constructor el cual incializa el Frame,los botones con sus atributos y todo el pex
        initComponents();
        material = new MaterialLog(); //  Creo la instancia de inventario 
        ListarMaterial(); //Listo las computadoras
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnBuscar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setTitle("Articulos");
        setVisible(true);
        getContentPane().setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setDefaultRenderer(Object.class,new Table_Img());
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(80);
        /*jTable1.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (jTable1.getSelectedRow()>=0)){
                        int filaSeleccionada = jTable1.getSelectedRow();
                        pc = (modeloTabla.DamePc(filaSeleccionada);
                            setPc(pc);
                        }
                    }
                }
            );*/
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(jTable1);

            getContentPane().add(jScrollPane2);
            jScrollPane2.setBounds(8, 0, 1140, 550);

            jBtnBuscar.setText("Buscar");
            jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnBuscarActionPerformed(evt);
                }
            });
            getContentPane().add(jBtnBuscar);
            jBtnBuscar.setBounds(620, 660, 80, 30);

            jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextBuscarKeyTyped(evt);
                }
            });
            getContentPane().add(jTextBuscar);
            jTextBuscar.setBounds(440, 660, 170, 25);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orig_506983.jpg"))); // NOI18N
            jLabel2.setText("jLabel2");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(0, 0, 1988, 1200);

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    private void ListarMaterial(){
        List<Material> listas = material.ListarMaterial(); //Buscar las computadoras en la base de datos y regresa la lista de todas las que esten
        modeloTabla = new ModeloTablaMaterial(listas);// Crea el modelo dependiendo la lista regresada
        jTable1.setModel(modeloTabla); // Y lo desppliega en el JText
        }    
    
    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed

        if(jTextBuscar.getText().isEmpty()){//Si se presiona buscar y el Jtext de buscar esta vacio entra
            List<Material> listas = material.ListarMaterial(); //hace la consulta que traes todos las pc en la BD
            modeloTabla = new ModeloTablaMaterial(listas);// crea el modelo
            jTable1.setModel(modeloTabla); // y lo ingresa al Jtable
        }else
        {
            List<Material> listas = material.BuscarMaterial(jTextBuscar.getText()); //Sino Bucar el texto ingresado en la base de datos
            modeloTabla = new ModeloTablaMaterial(listas); // Crea el modelo dependiendo la lista regresada
            jTable1.setModel(modeloTabla);  // Y lo ingresa en el Jtable
        }

    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jTextBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyTyped
        char cTeclaPresionada = evt.getKeyChar(); //Optiene las teclas presionadas
            if(cTeclaPresionada == KeyEvent.VK_ENTER)
        jBtnBuscar.doClick();//Si la tecla fue enter .doClick(); Simula que se presiono el boton
    }//GEN-LAST:event_jTextBuscarKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTable1.getRowHeight();
        if(row< jTable1.getRowCount() && row >=0 && column< jTable1.getColumnCount() && column >=0)
        {
            Object value = jTable1.getValueAt(row,column);
           int idMat=Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            if(value instanceof JButton)
            {
                ((JButton)value).doClick();
                PreCotizacion addCont = new PreCotizacion(null,true,idMat);
                addCont.setVisible(true);
                addCont.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                addCont.setAlwaysOnTop(true);                 
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
}
