/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import entidades.Cliente;
import entidades.Cotizacion;
import entidades.CotizarMaterial;
import entidades.Factura;
import entidades.Material;
import logico.ClienteLog;
import logico.CotizacionLog;
import logico.CotizarMaterialLog;
import logico.FacturaLog;
import logico.MaterialLog;
import static ventas.ClienteUsuario.nombreCompaniaClient;
import static ventas.Inventario.contenedorModulos;
import static ventas.Inventario.idCotizar;
import static ventas.RegistrarFrame.nuevoUsuario;
import static ventas.RegistrarFrame.txtNombreCompania;
import com.placeholder.PlaceHolder;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cardiell
 */
public class PagoFrame extends javax.swing.JInternalFrame implements Runnable{
MaterialLog material;
CotizarMaterialLog cotizaciones;
List<CotizarMaterial> Precotiz;
FacturaLog factura;
String fecha_vence;
Thread hilo;
Date Dates;
float APagar=0;
int y=0;
int CVC=0;
int numTar=0;

    /**
     * Creates new form PagoFrame
     */
    public PagoFrame() {
        initComponents();
        panelEfectivoExtendido.setVisible(false);
        panelTarjetaExtendido.setVisible(false);
        panelErrorCobro.setVisible(false);
        PlaceHolder numTarjeta = new PlaceHolder(txtTarjeta,"Numero de Tarjeta");
        PlaceHolder CVC = new PlaceHolder(txtCVC,"CVC");
        PlaceHolder nombreTarjeta = new PlaceHolder(txtNombreTarjeta,"Nombre en la Tarjeta");
        material = new MaterialLog();
        factura = new FacturaLog();
        cotizaciones = new CotizarMaterialLog();
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        Dates = new java.sql.Date(lnMilisegundos);        
        Precotiz= cotizaciones.ListarCotizarMaterial(idCotizar);
         fecha_vence= Dates.toString();
        int i=0;
        hilo = new Thread(this);
        hilo.start();                if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                ListarArticulo(Precotiz.get(i));
                i++;
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPago = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        panelEfectivo = new javax.swing.JPanel();
        rdbtnEfectivo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelEfectivoExtendido = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtPagado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        panelErrorCobro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelTarjeta = new javax.swing.JPanel();
        rdbtnTarjeta = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelTarjetaExtendido = new javax.swing.JPanel();
        txtTarjeta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCVC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNombreTarjeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalApagar = new javax.swing.JLabel();
        lblTotalProd = new javax.swing.JLabel();

        btnGroup.add(rdbtnEfectivo);
        btnGroup.add(rdbtnTarjeta);

        getContentPane().setLayout(null);

        panelPago.setBackground(new java.awt.Color(255, 255, 255));
        panelPago.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Tus Articulos");
        panelPago.add(jLabel1);
        jLabel1.setBounds(30, 40, 170, 20);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        panelPago.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 390, 10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panelEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        panelEfectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelEfectivo.setLayout(null);

        rdbtnEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnEfectivo.setMargin(new java.awt.Insets(4, 4, 4, 4));
        rdbtnEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rdbtnEfectivoMousePressed(evt);
            }
        });
        panelEfectivo.add(rdbtnEfectivo);
        rdbtnEfectivo.setBounds(17, 14, 30, 32);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setText("Efectivo");
        panelEfectivo.add(jLabel9);
        jLabel9.setBounds(46, 21, 59, 18);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/efectivo.png"))); // NOI18N
        panelEfectivo.add(jLabel10);
        jLabel10.setBounds(108, 10, 35, 35);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEfectivo.add(jPanel2);
        jPanel2.setBounds(10, 70, 100, 100);

        jPanel1.add(panelEfectivo);
        panelEfectivo.setBounds(10, 10, 620, 60);

        panelEfectivoExtendido.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        panelEfectivoExtendido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelEfectivoExtendido.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Pago con:");
        panelEfectivoExtendido.add(jLabel8);
        jLabel8.setBounds(40, 30, 140, 40);

        txtPagado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagadoKeyTyped(evt);
            }
        });
        panelEfectivoExtendido.add(txtPagado);
        txtPagado.setBounds(200, 30, 260, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Su cambio:");
        panelEfectivoExtendido.add(jLabel11);
        jLabel11.setBounds(40, 100, 150, 29);

        lblCambio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCambio.setText("0.00");
        panelEfectivoExtendido.add(lblCambio);
        lblCambio.setBounds(200, 100, 250, 30);

        panelErrorCobro.setBackground(new java.awt.Color(255, 255, 255));
        panelErrorCobro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alerta.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("El efectivo ingresado es menor que el total a cobrar.Verifique");

        javax.swing.GroupLayout panelErrorCobroLayout = new javax.swing.GroupLayout(panelErrorCobro);
        panelErrorCobro.setLayout(panelErrorCobroLayout);
        panelErrorCobroLayout.setHorizontalGroup(
            panelErrorCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErrorCobroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelErrorCobroLayout.setVerticalGroup(
            panelErrorCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelErrorCobroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEfectivoExtendido.add(panelErrorCobro);
        panelErrorCobro.setBounds(40, 160, 530, 40);

        jPanel1.add(panelEfectivoExtendido);
        panelEfectivoExtendido.setBounds(10, 70, 620, 210);

        panelTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        panelTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelTarjeta.setLayout(null);

        rdbtnTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnTarjeta.setMargin(new java.awt.Insets(4, 4, 4, 4));
        rdbtnTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rdbtnTarjetaMousePressed(evt);
            }
        });
        panelTarjeta.add(rdbtnTarjeta);
        rdbtnTarjeta.setBounds(10, 20, 30, 32);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setText("Nueva Tarjeta de Pago");
        panelTarjeta.add(jLabel4);
        jLabel4.setBounds(40, 23, 171, 18);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Visa.png"))); // NOI18N
        panelTarjeta.add(jLabel5);
        jLabel5.setBounds(232, 19, 30, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/amex.png"))); // NOI18N
        panelTarjeta.add(jLabel6);
        jLabel6.setBounds(268, 19, 30, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MasterCard.png"))); // NOI18N
        panelTarjeta.add(jLabel7);
        jLabel7.setBounds(196, 19, 30, 25);

        jPanel1.add(panelTarjeta);
        panelTarjeta.setBounds(10, 80, 620, 60);

        panelTarjetaExtendido.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        panelTarjetaExtendido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelTarjetaExtendido.setLayout(null);

        txtTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarjetaKeyTyped(evt);
            }
        });
        panelTarjetaExtendido.add(txtTarjeta);
        txtTarjeta.setBounds(39, 12, 407, 32);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        panelTarjetaExtendido.add(jComboBox1);
        jComboBox1.setBounds(39, 77, 91, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AAAA", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        panelTarjetaExtendido.add(jComboBox2);
        jComboBox2.setBounds(159, 77, 91, 28);

        jLabel13.setText("Comprueba tu número de tarjeta. ");
        panelTarjetaExtendido.add(jLabel13);
        jLabel13.setBounds(39, 50, 231, 18);

        jLabel14.setText("Introduce una fecha de vencimiento válida. ");
        panelTarjetaExtendido.add(jLabel14);
        jLabel14.setBounds(39, 109, 270, 18);

        txtCVC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCVCKeyTyped(evt);
            }
        });
        panelTarjetaExtendido.add(txtCVC);
        txtCVC.setBounds(316, 71, 130, 32);

        jLabel15.setText("Comprueba tu código de seguridad. ");
        panelTarjetaExtendido.add(jLabel15);
        jLabel15.setBounds(316, 109, 240, 18);
        panelTarjetaExtendido.add(txtNombreTarjeta);
        txtNombreTarjeta.setBounds(39, 129, 211, 32);

        jButton1.setBackground(new java.awt.Color(236, 82, 82));
        jButton1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar Pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelTarjetaExtendido.add(jButton1);
        jButton1.setBounds(39, 193, 188, 45);

        jLabel16.setText("Introduce tu nombre exactamente como aparece en tu tarjeta.");
        panelTarjetaExtendido.add(jLabel16);
        jLabel16.setBounds(39, 167, 440, 18);

        jPanel1.add(panelTarjetaExtendido);
        panelTarjetaExtendido.setBounds(10, 140, 620, 250);

        panelPago.add(jPanel1);
        jPanel1.setBounds(460, 70, 720, 400);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel2.setText("Total:");
        panelPago.add(jLabel2);
        jLabel2.setBounds(480, 30, 110, 36);

        txtTotalApagar.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        txtTotalApagar.setText("2534 ");
        panelPago.add(txtTotalApagar);
        txtTotalApagar.setBounds(600, 30, 190, 36);

        lblTotalProd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        panelPago.add(lblTotalProd);
        lblTotalProd.setBounds(180, 34, 200, 30);

        jScrollPane1.setViewportView(panelPago);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1190, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnEfectivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnEfectivoMousePressed
        panelEfectivoExtendido.setVisible(true);
        panelTarjetaExtendido.setVisible(false);
        txtTarjeta.setText("");
        txtCVC.setText("");
        txtNombreTarjeta.setText("");
        PlaceHolder numTarjeta = new PlaceHolder(txtTarjeta,"Numero de Tarjeta");
        PlaceHolder CVC = new PlaceHolder(txtCVC,"CVC");
        PlaceHolder nombreTarjeta = new PlaceHolder(txtNombreTarjeta,"Nombre en la Tarjeta");
        rdbtnEfectivo.setSelected(true);
        panelTarjeta.setBounds(10, 300, 620, 60);
    }//GEN-LAST:event_rdbtnEfectivoMousePressed

    private void rdbtnTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnTarjetaMousePressed
        panelTarjetaExtendido.setVisible(true);
        panelEfectivoExtendido.setVisible(false);
        rdbtnTarjeta.setSelected(true);
        txtPagado.setText("");
        lblCambio.setText("0.0");
        panelTarjeta.setBounds(10, 80, 620, 60);
    }//GEN-LAST:event_rdbtnTarjetaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"Pago realizado correctamente,Desea Factura?");
               if(opcion == 0)
               {
                             GuardarFactura();
                             this.dispose();
                             fac=null;
                             fac= new FacturaFrame();
                             contenedorModulos.add(fac);
                             contenedorModulos.getDesktopManager().maximizeFrame(fac);
                             fac.setVisible(true); 
                         
               }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagadoKeyTyped
                    char caracter = evt.getKeyChar(); //Optiene las teclas presionadas
                    if(((caracter < '0') ||
                      (caracter > '9')) &&
                      (caracter != '\b'))
                    {
                            evt.consume();
                    }           
            if(caracter == evt.VK_ENTER)
            {
                if(APagar<Float.valueOf(txtPagado.getText()))
                {
                    panelErrorCobro.setVisible(false);
                    lblCambio.setText(String.valueOf(Float.valueOf(txtPagado.getText())-APagar));
                    int opcion = JOptionPane.showConfirmDialog(this,"Pago realizado correctamente,Desea Factura?");
                        if(opcion == 0)
                        {
                             GuardarFactura();
                             this.dispose();
                             fac=null;
                             fac= new FacturaFrame();
                             contenedorModulos.add(fac);
                             contenedorModulos.getDesktopManager().maximizeFrame(fac);
                             fac.setVisible(true); 
                        }                
                }else
                    panelErrorCobro.setVisible(true);
                    
            }        
    }//GEN-LAST:event_txtPagadoKeyTyped

    private void txtCVCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCVCKeyTyped
        char caracter = evt.getKeyChar(); //Optiene las teclas presionadas
           if(((caracter < '0')||(caracter > '9')) &&(caracter != '\b'))
                evt.consume();
            if(CVC >2)
                evt.consume();
            if(caracter=='\b')
                CVC--;
            if(txtTarjeta.getText().isEmpty())
                CVC=0;
            CVC++;
    }//GEN-LAST:event_txtCVCKeyTyped

    private void txtTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarjetaKeyTyped
        char caracter = evt.getKeyChar(); 
            if(((caracter < '0') ||(caracter > '9')) && caracter != '\b') 
                evt.consume();
            if(numTar >15)
                evt.consume();
            if(caracter=='\b')
                numTar--;
            if(txtTarjeta.getText().isEmpty())
                numTar=0;                    
            if(numTar==4||numTar==8||numTar==12)
            {
                String tmp=txtTarjeta.getText();
                txtTarjeta.setText(tmp+" ");
            }
            numTar++;
    }//GEN-LAST:event_txtTarjetaKeyTyped

    private void ListarArticulo(CotizarMaterial cotizacion)
    {
        Material tmp =material.BuscarMaterialesId(cotizacion.getIdMaterial());
                
        panelArticulos = new JPanel();
        lblImagen = new JLabel();
        lblCantidad = new JLabel();
        lblNombreArticulo = new JLabel();
        lblTotal = new JLabel();
        panelArticulos.setBackground(new java.awt.Color(255, 255, 255));
        panelArticulos.setLayout(null);
        lblImagen.setBounds(10,11,60,54);
        ImageIcon lblPerfil= new ImageIcon(tmp.getImagen());
        Icon icono = new ImageIcon(lblPerfil.getImage().getScaledInstance(lblImagen.getWidth()-3,lblImagen.getHeight()-3,Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);     
        this.repaint();
        panelArticulos.add(lblImagen);
        lblImagen.setBounds(10, 11, 60, 54);

        lblNombreArticulo.setText(tmp.getNombreMaterial());
        panelArticulos.add(lblNombreArticulo);
        lblNombreArticulo.setBounds(80, 11, 261, 14);

        lblCantidad.setText(String.valueOf(cotizacion.getCantidad()));
        panelArticulos.add(lblCantidad);
        lblCantidad.setBounds(80, 31, 261, 14);

        lblTotal.setForeground(new java.awt.Color(255, 51, 51));
        lblTotal.setText(String.valueOf(cotizacion.getCantidad()*tmp.getPrecio()));
        panelArticulos.add(lblTotal);
        lblTotal.setBounds(80, 51, 261, 14);

        panelPago.add(panelArticulos);
        panelArticulos.setBounds(10, 90+y, 410, 70);
        y+=80;
        panelPago.setPreferredSize(new Dimension(1130,100+y));
        pack();
    }
   
   private void GuardarFactura()
   {
       
       ClienteLog cliente = new ClienteLog();
       Cliente tmp;
         if(nuevoUsuario)
            tmp= cliente.BuscarCliente(txtNombreCompania.getText());           
         else
            tmp=cliente.BuscarCliente(nombreCompaniaClient);
         Factura fac = new Factura(Dates,fechaVencimiento(),tmp.getIdCliente(),idCotizar);
       factura.AgregarFactura(fac);
   }
   
   private String fechaVencimiento()
   {
      String tmp = "";
      String anyo = fecha_vence.substring(0, 4).trim();
      String mes = fecha_vence.substring(5,7).trim();
      String dia = fecha_vence.substring(8,10).trim();
      int mestmp = Integer.valueOf(mes);
      int anyotmp = Integer.valueOf(anyo);
      if(mestmp==12)
      {
          mestmp=1;
          anyotmp++;
          anyo=String.valueOf(anyotmp);
      }
      else
      {
        mestmp++;
          switch(mestmp)
          {
              case 1:
                  mes="01";
              break;
              case 2:
                  mes="02";
              break;     
              case 3:
                  mes="03";
              break;
              case 4:
                  mes="04";
              break;
              case 5:
                  mes="05";
              break;
              case 6:
                  mes="06";
              break;
              case 7:
                  mes="07";
              break;
              case 8:
                  mes="08";
              break;
              case 9:
                  mes="09";
              break;
              default:
              break;
                      
          }
      }
      tmp=anyo+"-"+mes+"-"+dia;
     return tmp;

   }
            
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblTotalProd;
    private javax.swing.JPanel panelEfectivo;
    private javax.swing.JPanel panelEfectivoExtendido;
    private javax.swing.JPanel panelErrorCobro;
    private javax.swing.JPanel panelPago;
    private javax.swing.JPanel panelTarjeta;
    private javax.swing.JPanel panelTarjetaExtendido;
    private javax.swing.JRadioButton rdbtnEfectivo;
    private javax.swing.JRadioButton rdbtnTarjeta;
    private javax.swing.JTextField txtCVC;
    private javax.swing.JTextField txtNombreTarjeta;
    private javax.swing.JTextField txtPagado;
    private javax.swing.JTextField txtTarjeta;
    private javax.swing.JLabel txtTotalApagar;
    // End of variables declaration//GEN-END:variables
    private JPanel panelArticulos;
    private JLabel lblImagen;
    private JLabel lblCantidad;
    private JLabel lblNombreArticulo;
    private JLabel lblTotal;
    FacturaFrame fac;
    
    @Override
    public void run() {
         int total=0;
         int cantidad;
         float precio;
         float subtotal=0;
         int i=0;
         Material tmp;
        if(!Precotiz.isEmpty()){
            while(i< Precotiz.size())
            {
                cantidad=Precotiz.get(i).getCantidad();
                tmp =material.BuscarMaterialesId(Precotiz.get(i).getIdMaterial());
                
                precio = tmp.getPrecio();
                 total+= cantidad;
                 subtotal+=(precio*cantidad);
                i++;
            }
        }
        lblTotalProd.setText("("+total+")");
        APagar=subtotal;
        txtTotalApagar.setText(String.valueOf(subtotal));
        
    }    
}
