package ventas;


import entidades.Cliente;
import entidades.Direccion;
import entidades.Persona;
import logico.ClienteLog;
import logico.DireccionLog;
import logico.PersonaLog;
import static ventas.Inventario.btnCotizar;
import static ventas.Inventario.btnMaterial;
import static ventas.Inventario.btnReporteVentas;
import static ventas.Inventario.contenedorModulos;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Cardiell
 * @author JaquezAl
 */
public class RegistrarFrame extends javax.swing.JInternalFrame {
boolean presionado=false;
boolean fechaband=false;
public static boolean nuevoUsuario;
DireccionLog direccion;
PersonaLog persona;
ClienteLog cliente;

    /**
     * Creates new form Computadoras
     */

    public RegistrarFrame() { //Constructor el cual incializa el Frame,los botones con sus atributos y todo el pex
        initComponents();
        direccion = new DireccionLog();
        persona = new PersonaLog();
        cliente = new ClienteLog();
        nuevoUsuario=false;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtCp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCancelar = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombreCompania = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        ChooserDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtGuardar1 = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setTitle("Registrar Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 250, 1190, 10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ciudad:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 120, 70, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Colonia:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 120, 80, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Calle:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 190, 51, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Codigo Postal:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 190, 130, 20);

        txtCiudad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtCiudad);
        txtCiudad.setBounds(90, 110, 310, 30);

        txtColonia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtColonia);
        txtColonia.setBounds(700, 120, 360, 32);

        txtCalle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtCalle);
        txtCalle.setBounds(80, 180, 310, 30);

        txtCp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpKeyTyped(evt);
            }
        });
        jPanel1.add(txtCp);
        txtCp.setBounds(700, 180, 290, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(370, 50, 290, 10);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("DIRECCIÓN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 14, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 240);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCancelar.setText("Cancelar");
        jPanel2.add(txtCancelar);
        txtCancelar.setBounds(900, 440, 60, 14);

        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconGuardar.png"))); // NOI18N
        jBtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnGuardar);
        jBtnGuardar.setBounds(800, 380, 60, 60);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 130, 77, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Apellido Paterno:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(540, 120, 152, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Apellido Materno:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 195, 157, 22);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Fecha Nacimiento:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(530, 210, 167, 22);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Telefono:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 270, 83, 22);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Correo:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 270, 66, 22);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Nombre Compañia:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 360, 174, 22);

        txtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(txtNombre);
        txtNombre.setBounds(100, 125, 220, 30);

        txtApellidoP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(txtApellidoP);
        txtApellidoP.setBounds(700, 120, 220, 30);

        txtApellidoM.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(txtApellidoM);
        txtApellidoM.setBounds(180, 190, 220, 30);

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(txtCorreo);
        txtCorreo.setBounds(610, 270, 250, 30);

        txtNombreCompania.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(txtNombreCompania);
        txtNombreCompania.setBounds(210, 360, 220, 30);

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(120, 265, 210, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(360, 60, 300, 10);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("DATOS PERSONALES");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(380, 30, 280, 29);

        ChooserDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ChooserDateKeyPressed(evt);
            }
        });
        jPanel2.add(ChooserDate);
        ChooserDate.setBounds(700, 210, 170, 30);

        jLabel14.setText("*");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(410, 190, 10, 18);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEliminar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(890, 380, 60, 60);

        txtGuardar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtGuardar1.setText("Guardar");
        jPanel2.add(txtGuardar1);
        txtGuardar1.setBounds(810, 440, 50, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 250, 1190, 520);

        imgFondo.setBackground(new java.awt.Color(255, 255, 255));
        imgFondo.setForeground(new java.awt.Color(255, 255, 255));
        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgInternalFrame.png"))); // NOI18N
        getContentPane().add(imgFondo);
        imgFondo.setBounds(0, 0, 1320, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        //Si se presiona el boton Guardar obtiene todos los datos ingresados en los Jtext y jCheckBox
        int CP=0;
        String calle = txtCalle.getText();
        String ciudad = txtCiudad.getText();
        String colonia = txtColonia.getText();
        String apellidoM = txtApellidoM.getText();
        String apellidoP = txtApellidoP.getText();
        String correo = txtCorreo.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String nombreCompania = txtNombreCompania.getText();
        String fecha;
          fecha = FechaSql(ChooserDate.getDate().toString());
        if(Validar(fecha)){
        CP = Integer.valueOf(txtCp.getText());
        Direccion direc= new Direccion(ciudad,colonia,calle,CP);
        direccion.AgregarDireccion(direc);
        List<Direccion> temp = direccion.ListarDireccion();
        Persona per = new Persona(nombre,apellidoP,apellidoM,fecha,telefono,correo,temp.size());
        persona.AgregarPersona(per);
        List<Persona> temp1 = persona.ListarPersona();
        Cliente cli= new Cliente(nombreCompania,temp1.size());
        if (!cliente.AgregarCliente(cli)) {
            btnMaterial.setEnabled(true);
            btnCotizar.setEnabled(true);
            btnReporteVentas.setEnabled(true);
            this.dispose();
            pago=null;
            nuevoUsuario=true;
            pago = new PagoFrame();
            contenedorModulos.add(pago);
            contenedorModulos.getDesktopManager().maximizeFrame(pago);
            pago.setVisible(true);                
        } else {
                    System.exit(0);
                }
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void txtCpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyTyped
          char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_txtCpKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
          char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void ChooserDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChooserDateKeyPressed
        fechaband=true;
    }//GEN-LAST:event_ChooserDateKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
            btnMaterial.setEnabled(true);
            btnCotizar.setEnabled(true);
            btnReporteVentas.setEnabled(true);
            this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
  
    private boolean Validar(String fecha){
        int cont=0;
        int anyo=Integer.valueOf(fecha.substring(6,10));
        System.out.println(anyo);
        if(txtCiudad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Favor de introducir la Ciudad");
            return false;
        }else if(txtColonia.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir la Colonia");
             return false;
        }else if(txtCalle.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir la Calle");
             return false;
        }else if(txtCp.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir el Codigo Postal");
             return false;
        }else if(txtNombre.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir el Nombre");
             return false;
        }else if( txtApellidoP.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir Apellido Paterno");
             return false;
        }else if(txtTelefono.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir Telefono");
             return false;
        }else if(txtCorreo.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir su Correo");
             return false;
        }else if(txtNombreCompania.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"Favor de introducir el Nombre de la Compania");
             return false;
        }
        else if(anyo <1938 || anyo>2000)
        {
             JOptionPane.showMessageDialog(this,"Favor de introducir Fecha de Nacimiento Correcta");
            return false;
        }
        return true;
    }
    private String FechaSql(String fecha_a_filtrar){
        String dia="";
        String mes="";
        String anyo="";
        String fecha="";
        String temp;
        temp = fecha_a_filtrar.substring(4, 7).trim();
        switch(temp)
        {
            case "Jan":
                    mes="01";
            break;
            case "Feb":
                    mes="02";
            break;
            case "Mar":
                    mes="03";
            break;
            case "Apr":
                    mes="04";
            break;
            case "May":
                    mes="05";
            break;
            case "Jun":
                    mes="06";
            break;
           case "Jul":
                    mes="07";
            break;
            case "Aug":
                    mes="08";
            break;
            case "Sep":
                    mes="09";
            break;
            case "Oct":
                    mes="10";
            break;
            case "Nov":
                    mes="11";
            break;
            case "Dec":
                    mes="12";
            break;
            
        }
        dia = fecha_a_filtrar.substring(8, 10);
        anyo = fecha_a_filtrar.substring(24,28);
        fecha = dia+"-"+mes+"-"+anyo;
        return fecha;
        
    }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ChooserDate;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JLabel txtCancelar;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCp;
    private javax.swing.JLabel txtGuardar1;
    private javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtNombreCompania;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
PagoFrame pago;
}
