/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import entidades.Factura;
import logico.FacturaLog;
import modelotabla.ModeloTablaVentas;
import java.util.List;

/**
 *
 * @author Cardiell
 */
public class ReportedVentasFrame extends javax.swing.JInternalFrame {
FacturaLog inv;
Factura compras;
ModeloTablaVentas modeloTabla;
    /**
     * Creates new form ReportedVentasFrame
     */
    public ReportedVentasFrame() {
        initComponents();
        inv = new FacturaLog();
        ListarFactura();
    }
    
    public void ListarFactura()
    {

            List<Factura> listas = inv.MostrarFactura();
            tblVentas.setModel(new ModeloTablaVentas(listas));
            tblVentas.getRowSorter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 1120, 575);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa Articulo: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 640, 147, 22);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(550, 640, 150, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orig_506983.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1302, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if(txtBuscar.getText().isEmpty()){
            List<Factura> listas = inv.MostrarFactura();
            tblVentas.setModel(new ModeloTablaVentas(listas));
            tblVentas.getRowSorter();
        }else
        {
            List<Factura> listas = inv.BuscarFactura(txtBuscar.getText());
            tblVentas.setModel(new ModeloTablaVentas(listas));
            tblVentas.getRowSorter();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if(txtBuscar.getText().isEmpty()){
            List<Factura> listas = inv.MostrarFactura();

            tblVentas.setModel(new ModeloTablaVentas(listas));
            tblVentas.getRowSorter();
        }else
        {

            List<Factura> listas = inv.BuscarFactura(txtBuscar.getText());
            modeloTabla = new ModeloTablaVentas(listas);
            tblVentas.setModel(modeloTabla);
            tblVentas.getRowSorter();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
